### ISSUE TITLE
Code Review September 10 2018

### ISSUE THREAD

**Issue by iamciera** [DiscoveryDNA/TFBS_presence#8]
## Overall goal

Create a working script that is capable of looping through thousands of files. 

## Todo

- [x] This loop errors out on certain numbers. Why is that?  How can we fix it?  
- [x] Is this running the threshold correctly for each TFBS?  Can we have the function that tests the threshold on the random sequences run before we run this? Line 536 of `MSE.py` hardcodes which file to use. 
- [x] The threshold also needs to be run on each file input.  Maybe we can split all the threshold functions into their own file?? 
- [x] In line 80 in `MSE.py`, in the function description of `pipeline()`, Why is the threshold hardcoded in the funtion set to 80?
- [x] When you run `pipeline()` without a threshold, it takes forever to start running. What is it working on?

**Comment by joanne-chen** [comment]
Regarding bullet 4: the "**percentile** = 80" on line 512 simply means that the default value is 80, if the user does not specify a value for **percentile**. In other words, providing an argument for **percentile** is optional when using this function.
80 was an arbitrary number I set for the default
